// This file is auto-generated by @hey-api/openapi-ts

export type BackendModelsDtosAuthenticationDto = {
  userId?: bigint | null;
  firstName?: string | null;
  lastName?: string | null;
  username: string | null;
  passwordMd5?: string | null;
  token?: string | null;
};

export type BackendModelsDtosCurrentGameDto = {
  currentGameId?: bigint;
  quizId?: bigint;
  sessionId: string | null;
  isStarted?: boolean;
  isCompleted?: boolean;
  currentGameQuestions?: Array<BackendModelsDtosCurrentGameQuestionDto> | null;
  currentGameUsers?: Array<BackendModelsDtosCurrentGameUserDto> | null;
};

export type BackendModelsDtosCurrentGameQuestionDto = {
  isAnswered?: boolean;
  isCurrent?: boolean;
  isRobbingAllowed?: boolean;
  answerHint?: string | null;
  question: BackendModelsDtosQuestionDto;
};

export type BackendModelsDtosCurrentGameUserDto = {
  isCurrent?: boolean;
  isGameMaster?: boolean;
  points?: number;
  user: BackendModelsDtosUserDto;
};

export type BackendModelsDtosGameFlowDto = {
  userId?: bigint | null;
  username?: string | null;
  sessionId: string | null;
  questionId?: bigint | null;
  answer?: string | null;
  finalResults?: Array<BackendModelsDtosPlayerResult> | null;
  isGameCompleted?: boolean | null;
};

export type BackendModelsDtosPlayerResult = {
  userId: bigint;
  username: string | null;
  points: number;
  rank: number;
  isGameMaster: boolean;
};

export type BackendModelsDtosPreviousGameDto = {
  previousGameId?: bigint;
  sessionId: string | null;
  quizName: string | null;
  completedOn?: Date;
  previousGameUsers?: Array<BackendModelsDtosPreviousGameUserDto> | null;
};

export type BackendModelsDtosPreviousGameUserDto = {
  userId?: bigint;
  username: string | null;
  isGameMaster?: boolean;
  points?: number;
  rank?: number;
};

export type BackendModelsDtosQuestionDto = {
  questionId?: bigint;
  questionGroupId?: bigint | null;
  questionGroupName?: string | null;
  inquiry: string | null;
  answer: string | null;
  point?: number;
};

export type BackendModelsDtosQuestionGroupDto = {
  questionGroupId?: bigint;
  name: string | null;
  description?: string | null;
  questions?: Array<BackendModelsDtosQuestionDto> | null;
};

export type BackendModelsDtosQuizDto = {
  quizId?: bigint;
  name: string | null;
  questionGroups?: Array<BackendModelsDtosQuestionGroupDto> | null;
};

export type BackendModelsDtosUserDto = {
  userId?: bigint;
  firstName?: string | null;
  lastName?: string | null;
  username: string | null;
};

export type PostApiAuthenticationLoginData = {
  body?: BackendModelsDtosAuthenticationDto;
  path?: never;
  query?: never;
  url: "/api/Authentication/Login";
};

export type PostApiAuthenticationLoginResponses = {
  /**
   * OK
   */
  200: BackendModelsDtosAuthenticationDto;
};

export type PostApiAuthenticationLoginResponse = PostApiAuthenticationLoginResponses[keyof PostApiAuthenticationLoginResponses];

export type PostApiAuthenticationReauthenticateData = {
  body?: BackendModelsDtosAuthenticationDto;
  path?: never;
  query?: never;
  url: "/api/Authentication/Reauthenticate";
};

export type PostApiAuthenticationReauthenticateResponses = {
  /**
   * OK
   */
  200: BackendModelsDtosAuthenticationDto;
};

export type PostApiAuthenticationReauthenticateResponse = PostApiAuthenticationReauthenticateResponses[keyof PostApiAuthenticationReauthenticateResponses];

export type GetApiCurrentGameGetCurrentGameForCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/CurrentGame/GetCurrentGameForCurrentUser";
};

export type GetApiCurrentGameGetCurrentGameForCurrentUserResponses = {
  /**
   * OK
   */
  200: BackendModelsDtosCurrentGameDto;
};

export type GetApiCurrentGameGetCurrentGameForCurrentUserResponse =
  GetApiCurrentGameGetCurrentGameForCurrentUserResponses[keyof GetApiCurrentGameGetCurrentGameForCurrentUserResponses];

export type GetApiCurrentGameGetCurrentGameBySessionIdBySessionIdData = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: "/api/CurrentGame/GetCurrentGameBySessionId/{sessionId}";
};

export type GetApiCurrentGameGetCurrentGameBySessionIdBySessionIdResponses = {
  /**
   * OK
   */
  200: BackendModelsDtosCurrentGameDto;
};

export type GetApiCurrentGameGetCurrentGameBySessionIdBySessionIdResponse =
  GetApiCurrentGameGetCurrentGameBySessionIdBySessionIdResponses[keyof GetApiCurrentGameGetCurrentGameBySessionIdBySessionIdResponses];

export type PostApiCurrentGameCreateCurrentGameData = {
  body?: BackendModelsDtosCurrentGameDto;
  path?: never;
  query?: never;
  url: "/api/CurrentGame/CreateCurrentGame";
};

export type PostApiCurrentGameCreateCurrentGameResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutApiCurrentGameUpdateCurrentGameData = {
  body?: BackendModelsDtosCurrentGameDto;
  path?: never;
  query?: never;
  url: "/api/CurrentGame/UpdateCurrentGame";
};

export type PutApiCurrentGameUpdateCurrentGameResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteApiCurrentGameDeleteCurrentGameByCurrentGameIdData = {
  body?: never;
  path: {
    currentGameId: bigint;
  };
  query?: never;
  url: "/api/CurrentGame/DeleteCurrentGame/{currentGameId}";
};

export type DeleteApiCurrentGameDeleteCurrentGameByCurrentGameIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiGameFlowAddUserToCurrentGameData = {
  body?: BackendModelsDtosGameFlowDto;
  path?: never;
  query?: never;
  url: "/api/GameFlow/AddUserToCurrentGame";
};

export type PostApiGameFlowAddUserToCurrentGameResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiGameFlowStartGameData = {
  body?: BackendModelsDtosGameFlowDto;
  path?: never;
  query?: never;
  url: "/api/GameFlow/StartGame";
};

export type PostApiGameFlowStartGameResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiGameFlowSelectQuestionData = {
  body?: BackendModelsDtosGameFlowDto;
  path?: never;
  query?: never;
  url: "/api/GameFlow/SelectQuestion";
};

export type PostApiGameFlowSelectQuestionResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiGameFlowSubmitAnswerData = {
  body?: BackendModelsDtosGameFlowDto;
  path?: never;
  query?: never;
  url: "/api/GameFlow/SubmitAnswer";
};

export type PostApiGameFlowSubmitAnswerResponses = {
  /**
   * OK
   */
  200: boolean;
};

export type PostApiGameFlowSubmitAnswerResponse = PostApiGameFlowSubmitAnswerResponses[keyof PostApiGameFlowSubmitAnswerResponses];

export type PostApiGameFlowRobQuestionData = {
  body?: BackendModelsDtosGameFlowDto;
  path?: never;
  query?: never;
  url: "/api/GameFlow/RobQuestion";
};

export type PostApiGameFlowRobQuestionResponses = {
  /**
   * OK
   */
  200: boolean;
};

export type PostApiGameFlowRobQuestionResponse = PostApiGameFlowRobQuestionResponses[keyof PostApiGameFlowRobQuestionResponses];

export type PostApiGameFlowLeaveGameData = {
  body?: BackendModelsDtosGameFlowDto;
  path?: never;
  query?: never;
  url: "/api/GameFlow/LeaveGame";
};

export type PostApiGameFlowLeaveGameResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiGameFlowCancelGameData = {
  body?: BackendModelsDtosGameFlowDto;
  path?: never;
  query?: never;
  url: "/api/GameFlow/CancelGame";
};

export type PostApiGameFlowCancelGameResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiGameFlowSelectNextPlayerData = {
  body?: BackendModelsDtosGameFlowDto;
  path?: never;
  query?: never;
  url: "/api/GameFlow/SelectNextPlayer";
};

export type PostApiGameFlowSelectNextPlayerResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PostApiGameFlowAllowRobbingData = {
  body?: BackendModelsDtosGameFlowDto;
  path?: never;
  query?: never;
  url: "/api/GameFlow/AllowRobbing";
};

export type PostApiGameFlowAllowRobbingResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/Health";
};

export type GetApiHealthResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiHealthDetailedData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/Health/detailed";
};

export type GetApiHealthDetailedResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiHealthDatabaseData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/Health/database";
};

export type GetApiHealthDatabaseResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiHealthMetricsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/Health/metrics";
};

export type GetApiHealthMetricsResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiPreviousGameGetPreviousGamesForCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/PreviousGame/GetPreviousGamesForCurrentUser";
};

export type GetApiPreviousGameGetPreviousGamesForCurrentUserResponses = {
  /**
   * OK
   */
  200: Array<BackendModelsDtosPreviousGameDto>;
};

export type GetApiPreviousGameGetPreviousGamesForCurrentUserResponse =
  GetApiPreviousGameGetPreviousGamesForCurrentUserResponses[keyof GetApiPreviousGameGetPreviousGamesForCurrentUserResponses];

export type GetApiPreviousGameGetPreviousGameBySessionIdBySessionIdData = {
  body?: never;
  path: {
    sessionId: string;
  };
  query?: never;
  url: "/api/PreviousGame/GetPreviousGameBySessionId/{sessionId}";
};

export type GetApiPreviousGameGetPreviousGameBySessionIdBySessionIdResponses = {
  /**
   * OK
   */
  200: BackendModelsDtosPreviousGameDto;
};

export type GetApiPreviousGameGetPreviousGameBySessionIdBySessionIdResponse =
  GetApiPreviousGameGetPreviousGameBySessionIdBySessionIdResponses[keyof GetApiPreviousGameGetPreviousGameBySessionIdBySessionIdResponses];

export type GetApiQuestionGetQuestionsForCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/Question/GetQuestionsForCurrentUser";
};

export type GetApiQuestionGetQuestionsForCurrentUserResponses = {
  /**
   * OK
   */
  200: Array<BackendModelsDtosQuestionDto>;
};

export type GetApiQuestionGetQuestionsForCurrentUserResponse = GetApiQuestionGetQuestionsForCurrentUserResponses[keyof GetApiQuestionGetQuestionsForCurrentUserResponses];

export type GetApiQuestionGetQuestionsByQuestionGroupIdByQuestionGroupIdData = {
  body?: never;
  path: {
    questionGroupId: bigint;
  };
  query?: never;
  url: "/api/Question/GetQuestionsByQuestionGroupId/{questionGroupId}";
};

export type GetApiQuestionGetQuestionsByQuestionGroupIdByQuestionGroupIdResponses = {
  /**
   * OK
   */
  200: Array<BackendModelsDtosQuestionDto>;
};

export type GetApiQuestionGetQuestionsByQuestionGroupIdByQuestionGroupIdResponse =
  GetApiQuestionGetQuestionsByQuestionGroupIdByQuestionGroupIdResponses[keyof GetApiQuestionGetQuestionsByQuestionGroupIdByQuestionGroupIdResponses];

export type GetApiQuestionGetQuestionByQuestionIdData = {
  body?: never;
  path: {
    questionId: bigint;
  };
  query?: never;
  url: "/api/Question/GetQuestion/{questionId}";
};

export type GetApiQuestionGetQuestionByQuestionIdResponses = {
  /**
   * OK
   */
  200: BackendModelsDtosQuestionDto;
};

export type GetApiQuestionGetQuestionByQuestionIdResponse = GetApiQuestionGetQuestionByQuestionIdResponses[keyof GetApiQuestionGetQuestionByQuestionIdResponses];

export type PostApiQuestionCreateQuestionData = {
  body?: BackendModelsDtosQuestionDto;
  path?: never;
  query?: never;
  url: "/api/Question/CreateQuestion";
};

export type PostApiQuestionCreateQuestionResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutApiQuestionUpdateQuestionData = {
  body?: BackendModelsDtosQuestionDto;
  path?: never;
  query?: never;
  url: "/api/Question/UpdateQuestion";
};

export type PutApiQuestionUpdateQuestionResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteApiQuestionDeleteQuestionByQuestionIdData = {
  body?: never;
  path: {
    questionId: bigint;
  };
  query?: never;
  url: "/api/Question/DeleteQuestion/{questionId}";
};

export type DeleteApiQuestionDeleteQuestionByQuestionIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiQuestionGroupGetQuestionGroupsForCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/QuestionGroup/GetQuestionGroupsForCurrentUser";
};

export type GetApiQuestionGroupGetQuestionGroupsForCurrentUserResponses = {
  /**
   * OK
   */
  200: Array<BackendModelsDtosQuestionGroupDto>;
};

export type GetApiQuestionGroupGetQuestionGroupsForCurrentUserResponse =
  GetApiQuestionGroupGetQuestionGroupsForCurrentUserResponses[keyof GetApiQuestionGroupGetQuestionGroupsForCurrentUserResponses];

export type GetApiQuestionGroupGetQuestionGroupsByQuizIdByQuizIdData = {
  body?: never;
  path: {
    quizId: bigint;
  };
  query?: never;
  url: "/api/QuestionGroup/GetQuestionGroupsByQuizId/{quizId}";
};

export type GetApiQuestionGroupGetQuestionGroupsByQuizIdByQuizIdResponses = {
  /**
   * OK
   */
  200: Array<BackendModelsDtosQuestionGroupDto>;
};

export type GetApiQuestionGroupGetQuestionGroupsByQuizIdByQuizIdResponse =
  GetApiQuestionGroupGetQuestionGroupsByQuizIdByQuizIdResponses[keyof GetApiQuestionGroupGetQuestionGroupsByQuizIdByQuizIdResponses];

export type GetApiQuestionGroupGetQuestionGroupByQuestionGroupIdData = {
  body?: never;
  path: {
    questionGroupId: bigint;
  };
  query?: never;
  url: "/api/QuestionGroup/GetQuestionGroup/{questionGroupId}";
};

export type GetApiQuestionGroupGetQuestionGroupByQuestionGroupIdResponses = {
  /**
   * OK
   */
  200: BackendModelsDtosQuestionGroupDto;
};

export type GetApiQuestionGroupGetQuestionGroupByQuestionGroupIdResponse =
  GetApiQuestionGroupGetQuestionGroupByQuestionGroupIdResponses[keyof GetApiQuestionGroupGetQuestionGroupByQuestionGroupIdResponses];

export type PostApiQuestionGroupCreateQuestionGroupData = {
  body?: BackendModelsDtosQuestionGroupDto;
  path?: never;
  query?: never;
  url: "/api/QuestionGroup/CreateQuestionGroup";
};

export type PostApiQuestionGroupCreateQuestionGroupResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutApiQuestionGroupUpdateQuestionGroupData = {
  body?: BackendModelsDtosQuestionGroupDto;
  path?: never;
  query?: never;
  url: "/api/QuestionGroup/UpdateQuestionGroup";
};

export type PutApiQuestionGroupUpdateQuestionGroupResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteApiQuestionGroupDeleteQuestionGroupByQuestionGroupIdData = {
  body?: never;
  path: {
    questionGroupId: bigint;
  };
  query?: never;
  url: "/api/QuestionGroup/DeleteQuestionGroup/{questionGroupId}";
};

export type DeleteApiQuestionGroupDeleteQuestionGroupByQuestionGroupIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiQuizGetQuizzesForCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/Quiz/GetQuizzesForCurrentUser";
};

export type GetApiQuizGetQuizzesForCurrentUserResponses = {
  /**
   * OK
   */
  200: Array<BackendModelsDtosQuizDto>;
};

export type GetApiQuizGetQuizzesForCurrentUserResponse = GetApiQuizGetQuizzesForCurrentUserResponses[keyof GetApiQuizGetQuizzesForCurrentUserResponses];

export type GetApiQuizGetQuizByCurrentGameIdByCurrentGameIdData = {
  body?: never;
  path: {
    currentGameId: bigint;
  };
  query?: never;
  url: "/api/Quiz/GetQuizByCurrentGameId/{currentGameId}";
};

export type GetApiQuizGetQuizByCurrentGameIdByCurrentGameIdResponses = {
  /**
   * OK
   */
  200: BackendModelsDtosQuizDto;
};

export type GetApiQuizGetQuizByCurrentGameIdByCurrentGameIdResponse =
  GetApiQuizGetQuizByCurrentGameIdByCurrentGameIdResponses[keyof GetApiQuizGetQuizByCurrentGameIdByCurrentGameIdResponses];

export type GetApiQuizGetQuizByQuizIdData = {
  body?: never;
  path: {
    quizId: bigint;
  };
  query?: never;
  url: "/api/Quiz/GetQuiz/{quizId}";
};

export type GetApiQuizGetQuizByQuizIdResponses = {
  /**
   * OK
   */
  200: BackendModelsDtosQuizDto;
};

export type GetApiQuizGetQuizByQuizIdResponse = GetApiQuizGetQuizByQuizIdResponses[keyof GetApiQuizGetQuizByQuizIdResponses];

export type PostApiQuizCreateQuizData = {
  body?: BackendModelsDtosQuizDto;
  path?: never;
  query?: never;
  url: "/api/Quiz/CreateQuiz";
};

export type PostApiQuizCreateQuizResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutApiQuizUpdateQuizData = {
  body?: BackendModelsDtosQuizDto;
  path?: never;
  query?: never;
  url: "/api/Quiz/UpdateQuiz";
};

export type PutApiQuizUpdateQuizResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteApiQuizDeleteQuizByQuizIdData = {
  body?: never;
  path: {
    quizId: bigint;
  };
  query?: never;
  url: "/api/Quiz/DeleteQuiz/{quizId}";
};

export type DeleteApiQuizDeleteQuizByQuizIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetApiUserGetCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/User/GetCurrentUser";
};

export type GetApiUserGetCurrentUserResponses = {
  /**
   * OK
   */
  200: BackendModelsDtosUserDto;
};

export type GetApiUserGetCurrentUserResponse = GetApiUserGetCurrentUserResponses[keyof GetApiUserGetCurrentUserResponses];

export type PostApiUserCreateUserData = {
  body?: BackendModelsDtosAuthenticationDto;
  path?: never;
  query?: never;
  url: "/api/User/CreateUser";
};

export type PostApiUserCreateUserResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type PutApiUserUpdateUserData = {
  body?: BackendModelsDtosUserDto;
  path?: never;
  query?: never;
  url: "/api/User/UpdateUser";
};

export type PutApiUserUpdateUserResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteApiUserDeleteUserByUserIdData = {
  body?: never;
  path: {
    userId: bigint;
  };
  query?: never;
  url: "/api/User/DeleteUser/{userId}";
};

export type DeleteApiUserDeleteUserByUserIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: "http://localhost:62233" | (string & {});
};
